networks:
  korp-network:
    driver: bridge
    name: korp-network

services:
  http-server-projeto-korp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-server-projeto-korp
    restart: unless-stopped
    networks:
      - korp-network
    
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - korp-network
    depends_on:
      http-server-projeto-korp:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - korp-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=/prometheus/'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/prometheus/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - korp-network
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      prometheus:
        condition: service_healthy